In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("data2.csv")

In [3]:
df.head()

fever  bodyPain  age  runnose  difbreath  infprob
0    109         0   14        1          1        1
1    105         1   59        0          0        1
2    109         0   95        1         -1        0
3    109         0   85        1          1        1
4    105         1   70        0          0        1

In [4]:
df.tail()

fever  bodyPain  age  runnose  difbreath  infprob
10    105         1   86        0          0        1
11    107         0   28        1         -1        0
12    110         0   71        1          1        1
13    105         1   91        0          0        1
14    105         0   45        1         -1        0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   fever      15 non-null     int64
 1   bodyPain   15 non-null     int64
 2   age        15 non-null     int64
 3   runnose    15 non-null     int64
 4   difbreath  15 non-null     int64
 5   infprob    15 non-null     int64
dtypes: int64(6)
memory usage: 784.0 bytes


In [6]:
df['fever'].value_counts()

105    7
109    4
103    2
110    1
107    1
Name: fever, dtype: int64

In [7]:
df['difbreath'].value_counts()

-1    5
 1    5
 0    5
Name: difbreath, dtype: int64

In [8]:
df.describe()

fever   bodyPain        age    runnose  difbreath    infprob
count   15.000000  15.000000  15.000000  15.000000  15.000000  15.000000
mean   106.266667   0.333333  55.000000   0.666667   0.000000   0.666667
std      2.344192   0.487950  30.057089   0.487950   0.845154   0.487950
min    103.000000   0.000000  14.000000   0.000000  -1.000000   0.000000
25%    105.000000   0.000000  25.000000   0.000000  -1.000000   0.000000
50%    105.000000   0.000000  59.000000   1.000000   0.000000   1.000000
75%    109.000000   1.000000  84.500000   1.000000   1.000000   1.000000
max    110.000000   1.000000  95.000000   1.000000   1.000000   1.000000

In [9]:
import numpy as np

In [10]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    test_set_size=int(len(data)*ratio)
    test_indices=shuffled[:test_set_size]
    train_indices=shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]

In [11]:
np.random.permutation(7)

array([4, 0, 5, 1, 6, 2, 3])

In [12]:
train,test=data_split(df,0.2)

In [13]:
train

fever  bodyPain  age  runnose  difbreath  infprob
13    105         1   91        0          0        1
5     109         0   22        1         -1        0
8     105         0   18        1         -1        0
2     109         0   95        1         -1        0
1     105         1   59        0          0        1
14    105         0   45        1         -1        0
4     105         1   70        0          0        1
7     105         1   84        0          0        1
10    105         1   86        0          0        1
12    110         0   71        1          1        1
3     109         0   85        1          1        1
6     103         0   38        1          1        1

In [14]:
test

fever  bodyPain  age  runnose  difbreath  infprob
9     103         0   19        1          1        1
11    107         0   28        1         -1        0
0     109         0   14        1          1        1

In [15]:
X_train=train[['fever','bodyPain','age','runnose','difbreath']]

In [16]:
X_train

fever  bodyPain  age  runnose  difbreath
13    105         1   91        0          0
5     109         0   22        1         -1
8     105         0   18        1         -1
2     109         0   95        1         -1
1     105         1   59        0          0
14    105         0   45        1         -1
4     105         1   70        0          0
7     105         1   84        0          0
10    105         1   86        0          0
12    110         0   71        1          1
3     109         0   85        1          1
6     103         0   38        1          1

In [17]:
X_train.to_numpy()

array([[105,   1,  91,   0,   0],
       [109,   0,  22,   1,  -1],
       [105,   0,  18,   1,  -1],
       [109,   0,  95,   1,  -1],
       [105,   1,  59,   0,   0],
       [105,   0,  45,   1,  -1],
       [105,   1,  70,   0,   0],
       [105,   1,  84,   0,   0],
       [105,   1,  86,   0,   0],
       [110,   0,  71,   1,   1],
       [109,   0,  85,   1,   1],
       [103,   0,  38,   1,   1]], dtype=int64)

In [18]:
X_test=test[['fever','bodyPain','age','runnose','difbreath']].to_numpy()

In [19]:
X_test

array([[103,   0,  19,   1,   1],
       [107,   0,  28,   1,  -1],
       [109,   0,  14,   1,   1]], dtype=int64)

In [20]:
Y_train=train[['infprob']].to_numpy().reshape(12,)
Y_test=test[['infprob']].to_numpy().reshape(3,)

In [21]:
Y_train

array([1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
clf=LogisticRegression()

In [24]:
clf.fit(X_train,Y_train)

LogisticRegression()

In [25]:
inputFeatures=[100,1,22,-1,1]
infProb=clf.predict_proba([inputFeatures])[0][1]

In [26]:
infProb

0.9740192391817803